/**
 * Curated editorial inventory for the Atlanta pilot's no-API categories
 * (Food, Groceries). Food/grocery deals have NO public deal API (see
 * docs/data-sources.md), so this is hand-curated editorial content — NOT scraped.
 * Each record carries its authoritative `sourceUrl` (the merchant's own promo
 * page) and required attribution. The EditorialProvider re-verifies against this
 * checked-in list: a deal stays confirmed until it is flagged `removed` or its
 * `expiresInDays` window lapses, modelling a source that no longer confirms it.
 *
 * Coordinates cluster in the dense Atlanta core (Downtown/Midtown/Old Fourth
 * Ward) so the density-first threshold (>=20 verified physical pilot deals within
 * 10mi) is reachable at the launch zone. Replace/extend with real curated deals;
 * later providers (Kroger, affiliate feeds) supersede these as credentials land.
 */
export interface EditorialDeal {
  id: string;
  title: string;
  merchant: string;
  category: 'food' | 'groceries';
  currentPriceMinor: number | null;
  originalPriceMinor: number | null;
  lat: number;
  lng: number;
  sourceUrl: string;
  /** Days from ingest until the offer lapses (drives expiry + re-verification). */
  expiresInDays: number;
  /** Curation flag: when true the source no longer confirms it (verify -> invalid). */
  removed?: boolean;
}

export const EDITORIAL_DEALS: EditorialDeal[] = [
  // --- Food: Downtown / Five Points / Castleberry Hill ---
  {
    id: 'food-rosas-byo',
    title: 'BOGO Pizza Slices',
    merchant: "Rosa's Pizza",
    category: 'food',
    currentPriceMinor: 599,
    originalPriceMinor: 1199,
    lat: 33.7525,
    lng: -84.3915,
    sourceUrl: 'https://example-rosas.test/atl/deals',
    expiresInDays: 9,
  },
  {
    id: 'food-thumbs-up',
    title: '$8 Brunch Plate',
    merchant: 'Thumbs Up Diner',
    category: 'food',
    currentPriceMinor: 800,
    originalPriceMinor: 1400,
    lat: 33.7556,
    lng: -84.3733,
    sourceUrl: 'https://example-thumbsup.test/specials',
    expiresInDays: 7,
  },
  {
    id: 'food-slutty-vegan',
    title: '15% Off Impossible Burger',
    merchant: 'Slutty Vegan',
    category: 'food',
    currentPriceMinor: 1190,
    originalPriceMinor: 1400,
    lat: 33.7561,
    lng: -84.4129,
    sourceUrl: 'https://example-sv.test/atl',
    expiresInDays: 12,
  },
  {
    id: 'food-busy-bee',
    title: 'Lunch Combo Deal',
    merchant: 'Busy Bee Cafe',
    category: 'food',
    currentPriceMinor: 1299,
    originalPriceMinor: 1899,
    lat: 33.7536,
    lng: -84.4097,
    sourceUrl: 'https://example-busybee.test/lunch',
    expiresInDays: 10,
  },
  {
    id: 'food-no-mas',
    title: '2-for-1 Tacos Tuesday',
    merchant: 'No Mas! Cantina',
    category: 'food',
    currentPriceMinor: 700,
    originalPriceMinor: 1400,
    lat: 33.7459,
    lng: -84.4012,
    sourceUrl: 'https://example-nomas.test/tacos',
    expiresInDays: 6,
  },
  {
    id: 'food-octane',
    title: '$2 Off Any Latte',
    merchant: 'Octane Coffee',
    category: 'food',
    currentPriceMinor: 300,
    originalPriceMinor: 500,
    lat: 33.7489,
    lng: -84.4083,
    sourceUrl: 'https://example-octane.test/coffee',
    expiresInDays: 14,
  },
  {
    id: 'food-ponce-city',
    title: 'Food Hall Happy Hour',
    merchant: 'Ponce City Market',
    category: 'food',
    currentPriceMinor: 900,
    originalPriceMinor: 1500,
    lat: 33.7726,
    lng: -84.3654,
    sourceUrl: 'https://example-pcm.test/hh',
    expiresInDays: 8,
  },
  {
    id: 'food-krog-street',
    title: 'Dumpling Combo',
    merchant: 'Krog Street Market',
    category: 'food',
    currentPriceMinor: 1100,
    originalPriceMinor: 1600,
    lat: 33.7546,
    lng: -84.3651,
    sourceUrl: 'https://example-ksm.test/dumplings',
    expiresInDays: 9,
  },
  {
    id: 'food-vortex',
    title: 'Burger + Fries Special',
    merchant: 'The Vortex',
    category: 'food',
    currentPriceMinor: 1500,
    originalPriceMinor: 2100,
    lat: 33.772,
    lng: -84.3517,
    sourceUrl: 'https://example-vortex.test/deal',
    expiresInDays: 11,
  },
  {
    id: 'food-mary-mac',
    title: 'Soul Food Plate Deal',
    merchant: "Mary Mac's Tea Room",
    category: 'food',
    currentPriceMinor: 1399,
    originalPriceMinor: 1999,
    lat: 33.7708,
    lng: -84.3793,
    sourceUrl: 'https://example-marymac.test/plate',
    expiresInDays: 7,
  },
  {
    id: 'food-varsity',
    title: 'Combo Meal $6',
    merchant: 'The Varsity',
    category: 'food',
    currentPriceMinor: 600,
    originalPriceMinor: 950,
    lat: 33.7713,
    lng: -84.3892,
    sourceUrl: 'https://example-varsity.test/combo',
    expiresInDays: 13,
  },
  {
    id: 'food-waffle',
    title: 'All-Star Special',
    merchant: 'Waffle House',
    category: 'food',
    currentPriceMinor: 799,
    originalPriceMinor: 1099,
    lat: 33.76,
    lng: -84.387,
    sourceUrl: 'https://example-wh.test/allstar',
    expiresInDays: 10,
  },
  // --- Groceries: Downtown / Midtown / O4W ---
  {
    id: 'groc-kroger-mid',
    title: '20% Off Produce',
    merchant: 'Kroger Midtown',
    category: 'groceries',
    currentPriceMinor: null,
    originalPriceMinor: null,
    lat: 33.7811,
    lng: -84.3835,
    sourceUrl: 'https://example-kroger.test/midtown/weekly',
    expiresInDays: 6,
  },
  {
    id: 'groc-publix-o4w',
    title: 'BOGO Pasta',
    merchant: 'Publix Old Fourth Ward',
    category: 'groceries',
    currentPriceMinor: 249,
    originalPriceMinor: 498,
    lat: 33.7649,
    lng: -84.3631,
    sourceUrl: 'https://example-publix.test/o4w/weekly',
    expiresInDays: 7,
  },
  {
    id: 'groc-whole-foods',
    title: '$5 Off $30 Grocery',
    merchant: 'Whole Foods Ponce',
    category: 'groceries',
    currentPriceMinor: null,
    originalPriceMinor: null,
    lat: 33.7723,
    lng: -84.3656,
    sourceUrl: 'https://example-wf.test/ponce/deals',
    expiresInDays: 8,
  },
  {
    id: 'groc-aldi-west',
    title: 'Weekly Grocery Markdowns',
    merchant: 'ALDI West End',
    category: 'groceries',
    currentPriceMinor: null,
    originalPriceMinor: null,
    lat: 33.7361,
    lng: -84.4131,
    sourceUrl: 'https://example-aldi.test/westend',
    expiresInDays: 9,
  },
  {
    id: 'groc-trader-joes',
    title: 'Seasonal Snack Deal',
    merchant: "Trader Joe's Midtown",
    category: 'groceries',
    currentPriceMinor: 399,
    originalPriceMinor: 599,
    lat: 33.7869,
    lng: -84.382,
    sourceUrl: 'https://example-tj.test/midtown',
    expiresInDays: 10,
  },
  {
    id: 'groc-sprouts',
    title: '15% Off Bulk Foods',
    merchant: 'Sprouts Farmers Market',
    category: 'groceries',
    currentPriceMinor: null,
    originalPriceMinor: null,
    lat: 33.77,
    lng: -84.365,
    sourceUrl: 'https://example-sprouts.test/bulk',
    expiresInDays: 11,
  },
  {
    id: 'groc-savi',
    title: 'Artisan Cheese Special',
    merchant: 'Savi Provisions',
    category: 'groceries',
    currentPriceMinor: 899,
    originalPriceMinor: 1299,
    lat: 33.7717,
    lng: -84.3674,
    sourceUrl: 'https://example-savi.test/cheese',
    expiresInDays: 7,
  },
  {
    id: 'groc-fresh-mkt',
    title: '$10 Off Meat Bundle',
    merchant: 'The Fresh Market',
    category: 'groceries',
    currentPriceMinor: null,
    originalPriceMinor: null,
    lat: 33.7905,
    lng: -84.3733,
    sourceUrl: 'https://example-fm.test/meat',
    expiresInDays: 9,
  },
  {
    id: 'groc-kroger-ponce',
    title: 'Digital Coupon: Cereal',
    merchant: 'Kroger Ponce',
    category: 'groceries',
    currentPriceMinor: 199,
    originalPriceMinor: 399,
    lat: 33.7716,
    lng: -84.3653,
    sourceUrl: 'https://example-kroger.test/ponce/coupons',
    expiresInDays: 6,
  },
  {
    id: 'groc-publix-mid',
    title: 'Buy 2 Get 1 Snacks',
    merchant: 'Publix Midtown',
    category: 'groceries',
    currentPriceMinor: 333,
    originalPriceMinor: 499,
    lat: 33.7838,
    lng: -84.3819,
    sourceUrl: 'https://example-publix.test/midtown/weekly',
    expiresInDays: 8,
  },
  {
    id: 'food-mediterranea',
    title: 'Falafel Wrap Deal',
    merchant: 'Mediterranea',
    category: 'food',
    currentPriceMinor: 850,
    originalPriceMinor: 1200,
    lat: 33.7553,
    lng: -84.3899,
    sourceUrl: 'https://example-med.test/wrap',
    expiresInDays: 12,
  },
  {
    id: 'food-dua-vietnamese',
    title: 'Pho Lunch Special',
    merchant: 'Dua Vietnamese Noodle Soup',
    category: 'food',
    currentPriceMinor: 1050,
    originalPriceMinor: 1450,
    lat: 33.7547,
    lng: -84.3886,
    sourceUrl: 'https://example-dua.test/pho',
    expiresInDays: 10,
  },
];
