-- Add the optional redemption-brand hint used by the iOS nearby-redemption
-- finder (e.g. "Apple Store"). Null for online-only programs.
-- NOTE: Prisma's autogenerated diff also emitted spurious DROP INDEX / ALTER
-- COLUMN ... DROP DEFAULT statements for the PostGIS `geog` generated column and
-- raw-SQL uuid defaults. Those are drift artifacts that would drop the spatial
-- index and break uuid generation; they are intentionally omitted. This
-- migration only adds the new column.
ALTER TABLE "deals" ADD COLUMN "redemption_brand" TEXT;
